# window border
window.active.border.color: #e4a667
window.inactive.border.color: #d6d65c

# ToggleKeybinds status indicator
window.active.indicator.toggled-keybind.color: #fd4663

# window titlebar background
window.active.title.bg.color: #e4a667
window.inactive.title.bg.color: #d6d65c

window.active.label.text.color: #251f18
window.inactive.label.text.color: #251f18
window.label.text.justify: center

# window button hover overlay
window.button.hover.bg.color: #362e25

# window buttons
window.active.button.unpressed.image.color: #251f18
window.inactive.button.unpressed.image.color: #251f18

# menu
menu.border.color: #251f18
menu.items.bg.color: #e4a667
menu.items.text.color: #251f18
menu.items.active.bg.color: #d6d65c
menu.items.active.text.color: #251f18
menu.separator.color: #251f18
menu.title.bg.color: #e4a667
menu.title.text.color: #251f18

# on screen display (window-cycle dialog)
osd.bg.color: #e4a667
osd.border.color: #251f18
osd.label.text.color: #251f18
osd.window-switcher.preview.border.color: #71685d
