# window border
window.active.border.color: #adc6ff
window.inactive.border.color: #bdc6e0

# ToggleKeybinds status indicator
window.active.indicator.toggled-keybind.color: #ffb4ab

# window titlebar background
window.active.title.bg.color: #adc6ff
window.inactive.title.bg.color: #bdc6e0

window.active.label.text.color: #102f60
window.inactive.label.text.color: #273044
window.label.text.justify: center

# window button hover overlay
window.button.hover.bg.color: #292a2e

# window buttons
window.active.button.unpressed.image.color: #102f60
window.inactive.button.unpressed.image.color: #102f60

# menu
menu.border.color: #102f60
menu.items.bg.color: #adc6ff
menu.items.text.color: #102f60
menu.items.active.bg.color: #bdc6e0
menu.items.active.text.color: #273044
menu.separator.color: #102f60
menu.title.bg.color: #adc6ff
menu.title.text.color: #102f60

# on screen display (window-cycle dialog)
osd.bg.color: #adc6ff
osd.border.color: #102f60
osd.label.text.color: #102f60
osd.window-switcher.preview.border.color: #8e909a
