# window border
window.active.border.color: #c37322
window.inactive.border.color: #a3a329

# ToggleKeybinds status indicator
window.active.indicator.toggled-keybind.color: #fd4663

# window titlebar background
window.active.title.bg.color: #c37322
window.inactive.title.bg.color: #a3a329

window.active.label.text.color: #fafaf9
window.inactive.label.text.color: #11110f
window.label.text.justify: center

# window button hover overlay
window.button.hover.bg.color: #ded6cf

# window buttons
window.active.button.unpressed.image.color: #fafaf9
window.inactive.button.unpressed.image.color: #fafaf9

# menu
menu.border.color: #fafaf9
menu.items.bg.color: #c37322
menu.items.text.color: #fafaf9
menu.items.active.bg.color: #a3a329
menu.items.active.text.color: #11110f
menu.separator.color: #fafaf9
menu.title.bg.color: #c37322
menu.title.text.color: #fafaf9

# on screen display (window-cycle dialog)
osd.bg.color: #c37322
osd.border.color: #fafaf9
osd.label.text.color: #fafaf9
osd.window-switcher.preview.border.color: #9d7f5e
