-- Auto-generated by Noctalia. Do not edit by hand.
return {
	bg      = "{{ colors.surface.default.hex }}",
	fg      = "{{ colors.on_surface.default.hex }}",
	accent  = "{{ colors.primary.default.hex }}",
	on_accent = "{{ colors.on_primary.default.hex }}",

	branch_color         = "{{ colors.primary.default.hex }}",
	remote_branch_color  = "{{ colors.secondary.default.hex }}",
	tag_color            = "{{ colors.tertiary.default.hex }}",
	commit_color         = "{{ colors.secondary.default.hex }}",
	behind_remote_color  = "{{ colors.error.default.hex }}",
	ahead_remote_color   = "{{ colors.primary.default.hex }}",
	stashes_color        = "{{ colors.outline.default.hex }}",
	state_color          = "{{ colors.error.default.hex }}",
	staged_color         = "{{ colors.tertiary.default.hex }}",
	unstaged_color       = "{{ colors.secondary.default.hex }}",
	untracked_color      = "{{ colors.on_surface_variant.default.hex }}",
}
