#yazi.toml
[mgr]
show_hidden = true

[opener]
edit = [
	{ run = 'micro "$@"', block = true, desc = "micro", for = "unix"}
]

[open]
prepend_rules = [
	{ mime = "text/*", use = "edit"}
]

[plugin]
prepend_preloaders = [
  # Do not preload files in mounted locations:
  # Environment variable won't work here.
  # Using absolute path instead.
  { url = "/run/user/1000/gvfs/**/*", run = "noop" },

  # For mounted hard disk/drive
  #{ url = "/run/media/sebastian/**/*", run = "noop" },
]
prepend_previewers = [
  # Allow to preview folder.
  { url = "*/", run = "folder" },

  # Do not previewing files in mounted locations.
  # Uncomment the line below to allow previewing text files.
  # { mime = "{text/*,application/x-subrip}", run = "code" },

  # Using absolute path.
  { url = "/run/user/1000/gvfs/**/*", run = "noop" },

  # For mounted hard disk/drive.
  #{ url = "/run/media/sebastian/**/*", run = "noop" },
]

[[plugin.prepend_fetchers]]
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
url   = "*/"
run   = "git"
group = "git"
