#!/bin/bash

# -----------------------
# CONFIGURATION
# -----------------------
TARGET_KB=9500                  # 9.5MB (Leaves a 0.5MB container safety margin for Discord)
MAX_BYTES=$((10 * 1024 * 1024)) # 10MB limit in bytes
AUDIO_BITRATE=96                # 96k AAC
THREADS=3
JOBS=4

COMPRESSED_DIR="./compressed"
mkdir -p "$COMPRESSED_DIR"

# -----------------------
# FUNCTION
# -----------------------
process_file() {
  f="$1"
  [ -f "$f" ] || return

  base="$(basename "${f%.*}")"
  output="$COMPRESSED_DIR/${base}_compressed.mp4"
  passlog="$COMPRESSED_DIR/${base}_passlog"

  # Skip if already exists
  if [ -f "$output" ]; then
    echo "⏩ Skipping '$f' — already exists."
    return
  fi

  # 1. Check if the original is already under 10MB
  orig_size=$(stat -c%s "$f" 2>/dev/null || echo 0)
  if [ "$orig_size" -lt "$MAX_BYTES" ] && [ "$orig_size" -gt 0 ]; then
    echo "  ✓ '$f' is already under 10MB. Copying..."
    cp "$f" "$output"
    return
  fi

  # 2. Get exact duration
  duration=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$f")
  if [ -z "$duration" ]; then
    return
  fi

  # 3. Calculate mathematically perfect video bitrate
  video_bitrate=$(awk "BEGIN {print int(($TARGET_KB * 8 / $duration) - $AUDIO_BITRATE)}")

  # Skip if the video is extremely long
  if [ "$video_bitrate" -le 50 ]; then
    echo "  ✗ '$f' is too long to fit in 10MB. Skipping."
    return
  fi

  # 4. Smart Scaling
  if [ "$video_bitrate" -lt 3000 ]; then
    SCALE="-vf scale=-2:720"
  else
    SCALE=""
  fi

  echo "▶ Encoding '$f' at ${video_bitrate}k bitrate..."

  # PASS 1: Analyzes the video motion (Using mp4 dummy output to silence timestamp errors)
  # Note: Added '-profile:v high' for a free 5% compression efficiency boost!
  ffmpeg -y -i "$f" -c:v libx264 -preset slow -profile:v high $SCALE -b:v "${video_bitrate}k" \
         -pass 1 -passlogfile "$passlog" -an -f mp4 /dev/null \
         -threads "$THREADS" -loglevel error

  # PASS 2: Encodes the final video
  ffmpeg -y -i "$f" -c:v libx264 -preset slow -profile:v high $SCALE -b:v "${video_bitrate}k" \
         -pass 2 -passlogfile "$passlog" -c:a aac -b:a "${AUDIO_BITRATE}k" \
         -threads "$THREADS" "$output" -loglevel error

  # Clean up the passlog files generated by x264
  rm -f "${passlog}"*.log "${passlog}"*.mbtree

  # Final size check
  size=$(stat -c%s "$output" 2>/dev/null || echo 0)
  echo "  ✓ Done! Size: $((size / 1024 / 1024)) MB"
}

export -f process_file
export TARGET_KB MAX_BYTES AUDIO_BITRATE THREADS COMPRESSED_DIR

# -----------------------
# PARALLEL EXECUTION
# -----------------------
find . -maxdepth 1 -type f \( -iname '*.mp4' -o -iname '*.mkv' \) -print0 | \
  xargs -0 -n1 -P"$JOBS" bash -c 'process_file "$@"' _
